name: Storybook

on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: |
          cd storybook
          yarn install --frozen-lockfile
          yarn build
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Node.js dependencies
        run: |
          cd storybook
          yarn install --frozen-lockfile

      - name: Lint Action
        uses: wearerequired/lint-action@v1.10.0
        with:
          eslint: true
      # - run: |
      #     cd storybook
      #     yarn install --frozen-lockfile
      #     yarn lint
