name: Storybook

on:
  pull_request:
jobs:
  storybook-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: |
          cd storybook
          yarn install --frozen-lockfile
          yarn build
  storybook-lint:
    runs-on: ubuntu-latest

    steps:
      - name: checkout branch
        uses: actions/checkout@v2

      - name: run eslint
        run: |
          cd storybook
          yarn install --frozen-lockfile
          yarn eslint
      # - run: |
      #     cd storybook
      #     yarn install --frozen-lockfile
      #     yarn lint
