name: CI

on:
  pull_request:
jobs:
  storybook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build
        run: |
          cd storybook
          yarn install --frozen-lockfile
          yarn eslint
          yarn build
          
