name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - run: cd storybook
    - run: yarn install --frozen-lockfile
    - run: yarn build
    - run: git push origin `git subtree split --prefix storybook/dist master`:gh --force
